# Generated by Django 4.1.3 on 2022-11-09 16:03

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=randomslugfield.fields.RandomSlugField(
                blank=True, editable=False, length=9, max_length=9, unique=True
            ),
        ),
    ]
