# Generated by Django 4.1.3 on 2022-11-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="message",
            new_name="content",
        ),
    ]
