# Generated by Django 4.1.3 on 2022-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_rename_message_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.CharField(default="/static/images/home.jpg", max_length=300),
            preserve_default=False,
        ),
    ]
